### ISSUE TITLE
WHO5 update

### ISSUE THREAD

**Issue by DanielAmsel** [Neuropathology-Giessen/GIN-DNA-Panel-Details#7]
### Novel WHO5 classification based on Louis et al. The 2021 WHO Classification of CNS Tumors

- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#8
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#9
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#10
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#11
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#12
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#13
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#14
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#15
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#16
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#17
- [ ] Neuropathology-Giessen/GIN-RNA-Panel-Details#2
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#19
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#20
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#21
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#22
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#23
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#24
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#25
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#26
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#27
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#28
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#29
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#30
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#31
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#32
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#33
- [ ] Neuropathology-Giessen/GIN-RNA-Panel-Details#4
- [ ] Neuropathology-Giessen/GIN-DNA-Panel-Details#35
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#36
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#37
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#38
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#39
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#40
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#41
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#42
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#43
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#45
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#44
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#46
- [ ] Neuropathology-Giessen/GIN-RNA-Panel-Details#3
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#48
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#49
- [x] Neuropathology-Giessen/GIN-DNA-Panel-Details#50
